export const tagSuggestions = [
  { value: "audio processing", label: "Audio Processing" },
  { value: "video editing", label: "Video Editing" },
  { value: "image editing", label: "Image Editing" },
  { value: "animation", label: "Animation" },
  { value: "sound effects", label: "Sound Effects" },
  { value: "music generation", label: "Music Generation" },
  { value: "video compression", label: "Video Compression" },
  { value: "augmented reality", label: "Augmented Reality" },
  { value: "virtual reality", label: "Virtual Reality" },
  { value: "3d modeling", label: "3D Modeling" },
  { value: "motion graphics", label: "Motion Graphics" },
  { value: "video rendering", label: "Video Rendering" },
  { value: "cinematography", label: "Cinematography" },
  { value: "color grading", label: "Color Grading" },
  { value: "interactive media", label: "Interactive Media" },
  { value: "multimedia integration", label: "Multimedia Integration" },
  { value: "multimedia frameworks", label: "Multimedia Frameworks" },
  { value: "transcoding", label: "Transcoding" },
  { value: "audio synthesis", label: "Audio Synthesis" },
  { value: "video streaming", label: "Video Streaming" },
  { value: "video analytics", label: "Video Analytics" },
  { value: "subtitling", label: "Subtitling" },
  { value: "green screen effects", label: "Green Screen Effects" },
  { value: "video stabilization", label: "Video Stabilization" },
  { value: "media conversion", label: "Media Conversion" },
  { value: "audio visualization", label: "Audio Visualization" },
  { value: "storyboarding", label: "Storyboarding" },
  { value: "multimedia authoring", label: "Multimedia Authoring" },
  { value: "multimodal fusion", label: "Multimodal Fusion" },
  { value: "interactive video", label: "Interactive Video" },
  { value: "machine learning", label: "Machine Learning" },
  { value: "natural language processing", label: "Natural Language Processing" },
  { value: "computer vision", label: "Computer Vision" },
  { value: "speech recognition", label: "Speech Recognition" },
  { value: "sentiment analysis", label: "Sentiment Analysis" },
  { value: "reinforcement learning", label: "Reinforcement Learning" },
  { value: "neural networks", label: "Neural Networks" },
  { value: "deep learning", label: "Deep Learning" },
  { value: "data annotation", label: "Data Annotation" },
  { value: "data augmentation", label: "Data Augmentation" },
  { value: "data preprocessing", label: "Data Preprocessing" },
  { value: "model training", label: "Model Training" },
  { value: "model evaluation", label: "Model Evaluation" },
  { value: "model deployment", label: "Model Deployment" },
  { value: "chatbots", label: "Chatbots" },
  { value: "virtual assistants", label: "Virtual Assistants" },
  { value: "image generation", label: "Image Generation" },
  { value: "text generation", label: "Text Generation" },
  { value: "data visualization", label: "Data Visualization" },
  { value: "anomaly detection", label: "Anomaly Detection" },
  { value: "face recognition", label: "Face Recognition" },
  { value: "object detection", label: "Object Detection" },
  { value: "image classification", label: "Image Classification" },
  { value: "recommendation systems", label: "Recommendation Systems" },
  { value: "automl (automated machine learning)", label: "AutoML (Automated Machine Learning)" },
  { value: "explainable ai", label: "Explainable AI" },
  { value: "transfer learning", label: "Transfer Learning" },
  { value: "gans (generative adversarial networks)", label: "GANs (Generative Adversarial Networks)" },
  { value: "time series analysis", label: "Time Series Analysis" },
  { value: "feature engineering", label: "Feature Engineering" },
];
